//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sunny.ShopCNM.UITest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public Address()
        {
            this.Province = new HashSet<Province>();
            this.City = new HashSet<City>();
            this.County = new HashSet<County>();
            this.UserInfo = new HashSet<UserInfo>();
        }
    
        public int Id { get; set; }
        public int UserInfoId { get; set; }
    
        public virtual ICollection<Province> Province { get; set; }
        public virtual ICollection<City> City { get; set; }
        public virtual ICollection<County> County { get; set; }
        public virtual ICollection<UserInfo> UserInfo { get; set; }
    }
}
