//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sunny.ShopCNM.UITest.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class UserInfo
    {
        public UserInfo()
        {
            this.UGender = true;
            this.UCategory = 1;
        }

        public int Id { get; set; }
        [Required(ErrorMessage = "*必填项")]
        [RegularExpression(@"^[\u4e00-\u9fa5]{2,10}$", ErrorMessage = "*姓名格式不正确")]
        public string UName { get; set; }
        //[RegularExpression(@"(?=.*\d)(?=.*[a-z])(?=.*[A-Z])[a-zA-Z0-9]{8,10}", ErrorMessage = "*密码格式不正确")]
        [Compare("UPhone",ErrorMessage ="*两次密码不一致")]
        public string UPwd { get; set; }
        public bool UGender { get; set; }
        public Nullable<System.DateTime> UBirthday { get; set; }
        [RegularExpression(@"^(13[0-9]|14[5|7]|15[0|1|2|3|5|6|7|8|9]|18[0|1|2|3|5|6|7|8|9])\d{8}$",ErrorMessage ="手机号格式不正确")]
        public string UPhone { get; set; }
        public byte UCategory { get; set; }
        [Range(0,100000,ErrorMessage ="数据范围不正确")]
        public int AddressId { get; set; }

        public virtual Address Address { get; set; }
    }
}
